server:
  port: 8080
spring:
  session:
    timeout: 30
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.10:1521/orclpdb
    username: SCOTT
    password: Lipton1120